name: hello from python

on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        description: Choose env
        options:
          - dev
          - stg
          - prd
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
    branches:
      - dev
      - stg
      - main

jobs: 
  test-build:
    name: sample test build
    runs-on: "ubuntu-24.04"
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 20
    steps:
      - name: build docker image
        id: build_image
        run: |
          echo the webhook url is ${{ vars.SLACK_WEBHOOK_URL }}
          echo end
